default_context:
  project_name: 'card_game'
  project_slug: 'card_game'
  domain_main: 'card_game.com'
  domain_staging: 'stag.card_game.com'
  docker_swarm_stack_name_main: 'card_game-com'
  docker_swarm_stack_name_staging: 'stag-card_game-com'
  secret_key: '32'
  first_superuser: 'admin@card_game.com'
  first_superuser_password: 'password'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.card_game.com", "https://stag.card_game.com", "https://card_game.com", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'info@card_game.com'
  postgres_password: 'password'
  pgadmin_default_user: 'user'
  pgadmin_default_user_password: 'password'
  traefik_constraint_tag: 'card_game.com'
  traefik_constraint_tag_staging: 'stag.card_game.com'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:password'
  sentry_dsn: ''
  docker_image_prefix: 'fastapi'
  docker_image_backend: 'fastapibackend'
  docker_image_celeryworker: 'fastapiceleryworker'
  docker_image_frontend: 'fastapifrontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
