default_context:
  project_name: 'Card Game'
  project_slug: 'cardgame'
  domain_main: 'cardgame.com'
  domain_staging: 'stag.cardgame.com'
  docker_swarm_stack_name_main: 'cardgame-com'
  docker_swarm_stack_name_staging: 'stag-cardgame-com'
  secret_key: 'ca9c1d4509ec6c9b9550fecfab3817a9b87e5e06bcbfe94298b12ce14ca8e428'
  first_superuser: 'admin@cardgame.com'
  first_superuser_password: 'password'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.cardgame.com", "https://stag.cardgame.com", "https://cardgame.com", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'info@cardgame.com'
  postgres_password: 'password'
  pgadmin_default_user: 'admin@cardgame.com'
  pgadmin_default_user_password: 'password'
  traefik_constraint_tag: 'cardgame.com'
  traefik_constraint_tag_staging: 'stag.cardgame.com'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:password'
  sentry_dsn: ''
  docker_image_prefix: ''
  docker_image_backend: 'backend'
  docker_image_celeryworker: 'celeryworker'
  docker_image_frontend: 'frontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
