"""add global best model

Revision ID: ef0558e8250b
Revises: b9879ad15c0f
Create Date: 2021-04-24 16:02:52.498753

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "ef0558e8250b"
down_revision = "b9879ad15c0f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bestscore",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("min_open_count", sa.Integer(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_bestscore_id"), "bestscore", ["id"], unique=False)
    op.add_column("cardgame", sa.Column("open_count", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("cardgame", "open_count")
    op.drop_index(op.f("ix_bestscore_id"), table_name="bestscore")
    op.drop_table("bestscore")
    # ### end Alembic commands ###
