"""change game model

Revision ID: f0d80d54460a
Revises: f1bf02ac4b1f
Create Date: 2021-04-24 08:01:59.549138

"""


# revision identifiers, used by Alembic.
revision = "f0d80d54460a"
down_revision = "f1bf02ac4b1f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
