"""change game model

Revision ID: f1bf02ac4b1f
Revises: 17ce5497dff7
Create Date: 2021-04-24 08:00:02.840712

"""


# revision identifiers, used by Alembic.
revision = "f1bf02ac4b1f"
down_revision = "17ce5497dff7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
